<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>gigaw.at - shortening links with added lightning</title>

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <link rel="shortcut icon" href="/a/images/icon.png" />

  <cfset siteCss = [
    "/a/css/reset.css",
    "/a/css/flu.css",
    "/a/css/styles.css"
  ]>
  <cfstylesheet src="#siteCss#" path="/" media="screen,projection" minimize="true" />
  
  <link href='http://fonts.googleapis.com/css?family=Orbitron:400,900,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700' rel='stylesheet' type='text/css'>
 
</head>
<body>

	<div class="container sticky">