
	<div class="row">
		<div class="col6 colcenter">

			<h1>About Gigaw.at</h1>

			<p>
				Gigaw.at was created to fill a personal goal, and while I was at it I decided it would be nice to make it
				open for public use. As you may have guessed from the name of this application I have a little obsession
				with Back to the Future. <br />
				I know there are other link shortener services out there, but I wanted to write one.
			</p>

			<p>
				Note: Links are not affected by time travel in the process of shortening, but be careful of any lightning!
			</p>

			<p>
				If you need to get in touch about something try me at Twitter
				<a href="http://twitter.com/gigaw_at" title="Gigawat on Twitter">@gigaw_at</a>
			</p>

		</div>

	</div>
