

<div class="row">
  <div class="col6 colcenter">

	<cfoutput>

		<p id="copied" class="notification center hide microwatt">
			Link Copied link to Clipboard
		</p>

		<h1 id="copy" class="focus" title="Click to Copy">
			http://gigaw.at/?/#link.shortUrl#
		</h1>

		<p class="milliwatt">
			<i class="i title"></i>#link.title#
		</p>

		<p>
			<i class="i world"></i>#link.originalUrl#
		</p>

	</cfoutput>

	</div>
</div>
