
  <div class="row">
    <div class="col6 colcenter">

			<h1>FAQ</h1>

			<dl>
				<dt class="microwatt">What is Gigaw.at?</dt>
				<dd>
					Gigaw.at is a simple URL shortener, that is open to the public to use to shorten those long
					URLS that you would like to share on social networking sites, in emails, through chat rooms (IRC),
					etc.
				</dd>

				<dt class="microwatt">What's with the name?</dt>
				<dd>
					I like Back to the Future and I like to name my little projects with references from the movie
				</dd>

				<dt class="microwatt">What is powering Gigaw.at?</dt>
				<dd>
					Gigaw.at is using OpenBD and MongoDB
				</dd>

			</dl>

		</div>
	</div>
